### ISSUE TITLE
Mali

### ISSUE THREAD

**Issue by lacin96** [leon-anavi/tizen-sunxi#10]
Cant download

**Comment by leon-anavi** [comment]
Hi,

Please try again. On my side there is no problem cloning the repository:

```
leon@leon-ultrabook:~/github$ git clone https://github.com/leon-anavi/tizen-sunxi.git
Cloning into 'tizen-sunxi'...
remote: Counting objects: 56, done.
remote: Total 56 (delta 0), reused 0 (delta 0), pack-reused 56
Unpacking objects: 100% (56/56), done.
Checking connectivity... done.
```

After that follow the instructions for the README to build and run Tizen image with software grahics acceleration for Wayland on Allwinner devices.

Best regards, Leon
